version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.16.1
    container_name: vault-server
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - vault_config:/vault/config
    command: vault server -dev
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  redis:
    image: redis:7.0.12-alpine
    container_name: redis-server
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  spring-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      # Vault Configuration
      SPRING_CLOUD_VAULT_URI: "http://vault:8200"
      SPRING_CLOUD_VAULT_TOKEN: "root"
      SPRING_CLOUD_VAULT_KV_ENABLED: "true"
      SPRING_CLOUD_VAULT_KV_BACKEND: "secret"
      SPRING_CLOUD_VAULT_CONFIG_TIMEOUT: "15000" # 15 saniye

      # Redis Configuration
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_PASSWORD: ""

      # Application Profile
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      vault:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s # Uygulamanın başlaması için ek süre

networks:
  app-network:
    driver: bridge
    #ipam:
    #  config:
    #    - subnet: 172.20.0.0/16
    #    - gateway: 172.20.0.1

volumes:
  vault_data:
    driver: local
  vault_config:
    driver: local
  redis_data:
    driver: local